baseURL = "http://hugo-test.mysteriousfox.com/"
languageCode = "en-us"
title = "Mysterious Fox"
theme = "Mysteriousfox_theme"

[params]
    description = "My site description"

[menu]
#  [[menu.main]]
#    name = "Home"
#    pre = "paw"
#    url = "/"
#    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "folder"
    title  = "blog section"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "database"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Contact Me"
    pre = "female"
    url = "/ContactMe/"
    weight = 4